"""
Django settings for constr_store project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ==================== ALLOWED HOSTS & CSRF SETTINGS ====================
# Для разработки с ngrok разрешаем все поддомены ngrok
ALLOWED_HOSTS = [
    '.ngrok-free.app',          # Все поддомены ngrok-free.app
    '.ngrok.io',               # Все поддомены ngrok.io
    'localhost',
    '127.0.0.1',
    '[::1]',
    'stationery-0lp6.onrender.com',  # Ваш production домен
]

# CSRF trusted origins - ВСЕ домены ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',  # ВАЖНО: звездочка в начале для всех поддоменов
    'https://*.ngrok.io',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'https://stationery-0lp6.onrender.com',
]

# ==================== SECURITY SETTINGS FOR DEVELOPMENT ====================
# Для разработки отключаем некоторые security настройки
if DEBUG:
    SESSION_COOKIE_SECURE = False      # Для HTTP в разработке
    CSRF_COOKIE_SECURE = False         # Для HTTP в разработке
    SECURE_SSL_REDIRECT = False        # Не перенаправлять на HTTPS
    SECURE_HSTS_SECONDS = 0            # Отключаем HSTS для разработки
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # Cookies settings для разработки
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
    CSRF_COOKIE_SAMESITE = 'Lax'       # Для работы через ngrok

# ==================== DATABASE ====================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Try to use DATABASE_URL if available
try:
    import dj_database_url
    if config('DATABASE_URL', default=''):
        DATABASES['default'] = dj_database_url.parse(config('DATABASE_URL'))
except ImportError:
    pass
except Exception:
    pass

# ==================== APPLICATION DEFINITION ====================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    
    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # Local apps
    'accounts',
    'shop',
    'telegram_bot',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Оставляем включенным
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'constr_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.shop_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'constr_store.wsgi.application'

# ==================== PASSWORD VALIDATION ====================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== INTERNATIONALIZATION ====================
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# ==================== STATIC & MEDIA FILES ====================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==================== DEFAULT AUTO FIELD ====================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== DJANGO-ALLAUTH SETTINGS ====================
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Для разработки
ACCOUNT_EMAIL_REQUIRED = True

# ==================== CRISPY FORMS ====================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ==================== TELEGRAM BOT SETTINGS ====================
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_ADMIN_CHAT_ID = config('TELEGRAM_ADMIN_CHAT_ID', default='')

# ==================== SHOP CONTACTS ====================
SHOP_NAME = "Neznaika KG"
SHOP_PHONE_1 = "+996 504 38 44 33"
SHOP_PHONE_2 = "+996 707 54 53 64"
SHOP_PHONE_3 = "+996 706 00 42 40"
SHOP_INSTAGRAM = "https://www.instagram.com/neznaika_kg?igsh=MTdxZXdiamw0ZXR0cA=="
SHOP_ADDRESS_1 = "Дордой джунхай 5-й проход, 507-508"
SHOP_ADDRESS_2 = "Шанхай Шн25-26"
SHOP_MAP_URL = "https://2gis.kg/bishkek/geo/70030076969219714/74.617278,42.937095"

# ==================== EMAIL SETTINGS ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Для разработки используем консольный бэкенд
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ==================== PRODUCTION SECURITY SETTINGS ====================
if not DEBUG:
    # Production security settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Для production меняем ALLOWED_HOSTS
    ALLOWED_HOSTS = [
        'stationery-0lp6.onrender.com',
        'neznaika-kg.onrender.com',
        # Добавьте другие production домены
    ]
    
    # Для production меняем CSRF trusted origins
    CSRF_TRUSTED_ORIGINS = [
        'https://stationery-0lp6.onrender.com',
        'https://neznaika-kg.onrender.com',
        # Добавьте другие production домены
    ]

# ==================== LOGGING (опционально) ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if DEBUG else 'WARNING',
    },
}