# Generated by Django 6.0.1 on 2026-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_fix_orderitem_null_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Название банка')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('qr_code_image', models.ImageField(upload_to='qr_codes/', verbose_name='QR-код счета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('qr_code', 'QR-код')], default='stripe', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_payment_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные для QR-оплаты'),
        ),
    ]
