# Generated by Django 4.2.7 on 2026-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bankaccount_order_payment_method_order_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr_code', 'QR-код (мБанк)')], default='qr_code', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
