# Generated by Django 4.2.7 on 2026-02-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в Base64'),
        ),
    ]
