# Generated by Django 4.2.7 on 2026-02-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_data',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в Base64'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
