# Generated by Django 4.2.7 on 2026-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_image_data_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True, verbose_name='QR-код в Base64'),
        ),
    ]
